# Generated by Django 2.1.2 on 2018-10-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='group',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='story_length',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
